### ISSUE TITLE
domon里面不能回复

### ISSUE THREAD

**Issue by daofeng2015** [RedBeanN/node-mirai#1]
![QQ截图20200314132201](https://user-images.githubusercontent.com/14891398/76675674-da79d880-65f6-11ea-8da9-bf7af93e48b4.png)
![QQ截图20200314132217](https://user-images.githubusercontent.com/14891398/76675676-dc439c00-65f6-11ea-9464-cb49eebfac5f.png)
能正常连接上..但是qq不回复消息.还有作者能支持ws吗,那个消息回复速度更快点

**Comment by daofeng2015** [comment]
好吧...你这代码只能设置固定语句触发才能回复..我看错了..

**Comment by RedBeanN** [comment]
ws 见 #3
