### ISSUE TITLE
示例中的引用和撤回没作用

### ISSUE THREAD

**Issue by daofeng2015** [RedBeanN/node-mirai#13]
![image](https://user-images.githubusercontent.com/14891398/86952426-90a89580-c185-11ea-99b1-6bd75f53ada3.png)
提示引用报错状态码500,撤回直接报错了

**Comment by RedBeanN** [comment]
1. 示例的撤回是群聊中撤回带有“撤回”关键词的消息（需有权限）
2. 私聊引用确实问题 <del>复制代码复制错了</del>

**Comment by daofeng2015** [comment]
> 1. 示例的撤回是群聊中撤回带有“撤回”关键词的消息（需有权限）
> 2. 私聊引用确实问题 ~复制代码复制错了~

好吧..我应该在群聊中测试的..

**Comment by daofeng2015** [comment]
![QQ截图20200710162952](https://user-images.githubusercontent.com/14891398/87133958-a07dc200-c2ca-11ea-93d6-7b48eb9cf20c.png)
qu群聊测试引用正常,但是撤回还是出现报错

**Comment by daofeng2015** [comment]
注意:机器人不能撤回群主消息
