### ISSUE TITLE
如何监听添加好友请求

### ISSUE THREAD

**Issue by xiyuesaves** [RedBeanN/node-mirai#21]
我在翻阅文档时一直没有找到关于好友方面的操作介绍,尝试直接使用http-api的订阅事件或者根据node-mirai的命名类型进行修改也无法实现监听,请问下这是没有实现还是我的方法有问题
```
bot.on("NewFriendRequestEvent",data => {
	console.log(data);
})
// or
bot.on("newFriendRequest",data => {
	console.log(data);
})
```

**Comment by Talaxy009** [comment]
去看了下 [事件列表](https://github.com/RedBeanN/node-mirai/blob/master/src/events.json)，发现没有 `NewFriendRequestEvent` 对应的事件，应该是还没有实现。

**Comment by xiyuesaves** [comment]
> 去看了下 [事件列表](https://github.com/RedBeanN/node-mirai/blob/master/src/events.json)，发现没有 `NewFriendRequestEvent` 对应的事件，应该是还没有实现。

好的,谢谢解答

**Comment by Talaxy009** [comment]
已经实现处理好友申请啦！刚刚提交了PR，立马就通过了。
测试代码如下，可以使用：

```js
bot.on("newFriendRequest", (data) => {
    const { eventId, fromId, groupId, nick, message } = data;
    console.log(`新的好友申请: ${nick}[${fromId}] (${message}) 通过群:${groupId}`);
    bot.handleNewFriendRequest(eventId, fromId, groupId, 0, "你好"); //0同意，1拒绝，2拒绝并拉黑
});
```

不过有意思的是虽然 mirai-api-http 那边有提供接收回复消息的变量，但我无论是同意还是拒绝都收不到 "你好" 二字，你可以自行试试，初步判断不是我代码的问题= v =

**Comment by xiyuesaves** [comment]
好的!非常感谢 owo

Taozc <notifications@github.com> 于2021年1月8日周五 下午3:58写道：
