### ISSUE TITLE
如何获取到信息来源的群号或者QQ?

### ISSUE THREAD

**Issue by TQF-Moke** [RedBeanN/node-mirai#24]
![image](https://user-images.githubusercontent.com/24997752/105642061-463cfb00-5ec2-11eb-9581-5ac2ba7a04fb.png)
感觉这样写好像是不对的但是不知道怎么写才是正确的，希望大佬能够花几分钟解答一下，拜托了！

**Comment by Talaxy009** [comment]
信息来源不在 messageChain 中哦，群号在 sender.group.id 而 发送人QQ在 sender.id 中

**Comment by TQF-Moke** [comment]
> 信息来源不在messageChain中哦，群号在sender.group.id而发送人QQ在sender.id中

懂了！谢谢大佬指点！
