### ISSUE TITLE
支持 Websocket

### ISSUE THREAD

**Issue by RedBeanN** [RedBeanN/node-mirai#3]
``` javascript
const bot = new Mirai({
  // ...
  enableWebsocket: true // enable websocket
});
```

**Comment by daofeng2015** [comment]
> ```js
> const bot = new Mirai({
>   // ...
>   enableWebsocket: true // enable websocket
> });
> ```
const bot = new Mirai({
  host: 'ws://127.0.0.1:8080', // your server host
  authKey: 'AAAAAAAA',
  enableWebsocker:true,
  qq: 211995046 // your qq
});
sdk这边接受不到消息

**Comment by RedBeanN** [comment]
@daofeng2015 现在应该可以了，npm更新下试试看
