### ISSUE TITLE
随着console的自动更新，框架的auth认证通不过了。

### ISSUE THREAD

**Issue by moushicheng** [RedBeanN/node-mirai#31]
没有变动原先代码， host（http://127.0.0.1:8080）、authKey（114514）和setting.yml中host，port，authKey设置的一样。
失败截图：
此时mcl正常开启，能收发qq消息
![image](https://user-images.githubusercontent.com/54257412/125162743-240f0f00-e1bc-11eb-95ea-f5c55b39c44d.png)

设置截图:
![image](https://user-images.githubusercontent.com/54257412/125162626-89aecb80-e1bb-11eb-8d72-fec093aad33c.png)
![image](https://user-images.githubusercontent.com/54257412/125162629-8f0c1600-e1bb-11eb-8ab5-cac56cd3b64a.png)

如果还需要什么截图/未详尽阐述的地方，请联系我

**Comment by moushicheng** [comment]
![image](https://user-images.githubusercontent.com/54257412/125163137-528de980-e1be-11eb-8058-67c57792f36d.png)
我尝试打印了一下错误信息↑

**Comment by kirainmoe** [comment]
是否升级了 mirai-api-http 到 2.x ？2.x 的认证方式和 1.x 已经不同了，但此版本的 node-mirai 还没有支持。

**Comment by moushicheng** [comment]
> 是否升级了 mirai-api-http 到 2.x ？2.x 的认证方式和 1.x 已经不同了，但此版本的 node-mirai 还没有支持。

status指令显示：.mirai-api-http v1.10.0
![image](https://user-images.githubusercontent.com/54257412/125163344-4a827980-e1bf-11eb-8a9d-0144e3f50421.png)

**Comment by RedBeanN** [comment]
`mirai-api-http` 与 `mirai-console` 版本不兼容所致.
升级至 `mirai-api-http 1.12.0` 或将 `mirai-console-core` 版本回退至 `2.6` 即可
