### ISSUE TITLE
消息发不到群聊里面去是什么原因？

### ISSUE THREAD

**Issue by NekoAndLoli** [RedBeanN/node-mirai#37]
图片和消息可以正常发到私聊，但是发群里去就没有任何显示。
Console上可以看见消息应该是发出去了，powershell上也没有显示错误。

![P ) V2XOC}I @KITD`IW@B](https://user-images.githubusercontent.com/26484555/144558694-22574268-99c7-4e0d-b053-ef3da6adb160.png)

**Comment by kirainmoe** [comment]
触发腾讯的风控了。

**Comment by NekoAndLoli** [comment]
啊？怎么才能绕开这个？

**Comment by kirainmoe** [comment]
放着挂几天就好了。

**Comment by NekoAndLoli** [comment]
那过两天再看看

**Comment by RedBeanN** [comment]
风控导致
